#!/bin/bash
DIR=/etc/docker
SRC="${DIR}/daemon.json.${PPID}"
DST="${DIR}/daemon.json"
BINDIR=/usr/local/bin
${BINDIR}/ascend-docker-plugin-install-helper ${DST} ${SRC}
if [ "$?" != "0" ]; then
echo "create damon.json failed\n"
exit 1
fi
\mv ${SRC} ${DST} 
echo "create damom.json success\n"
