#!/bin/bash
DIR=/etc/docker
if [ ! -d "${DIR}" ]; then
mkdir ${DIR}
fi
SRC="${DIR}/daemon.json.${PPID}"
DST="${DIR}/daemon.json"
BINDIR=/usr/local/bin
${BINDIR}/ascend-docker-plugin-install-helper rm ${DST} ${SRC}
if [ "$?" != "0" ]; then
echo "del damon.json failed\n"
exit 1
fi
\mv ${SRC} ${DST} 
echo "del damom.json success\n"
