#!/bin/bash
DIR=/etc/docker
SRC="${DIR}/daemon.json.${PPID}"
DST="${DIR}/daemon.json"
if [ ! -f "${DST}" ]; then
exit 0
fi
BINDIR=/usr/bin
${BINDIR}/ascend-docker-plugin-install-helper rm ${DST} ${SRC}
if [ "$?" != "0" ]; then
echo "del damon.json failed\n"
exit 1
fi
\mv ${SRC} ${DST} 
echo "del damom.json success\n"
